Transaction tests for EIP-3860: Limit and meter initcode
ethereum/tests pull request #1012
Opened 2022-01-27 14:16 UTC by gumb0

2022-01-27 14:44 UTC, gumb0 commented on src/TransactionTestsFiller/ttData/DataTestInitCodeTooBigFiller.yml
> +        London+3860: "TR_InitCodeLimitExceeded"
This requires new rule in retesteth config:
```
      "TR_InitCodeLimitExceeded": "init code size limit exceeded"
```

2022-02-02 00:46 UTC, jochem-brouwer commented
Is this one an updated version of #990?

2022-02-02 13:51 UTC, gumb0 commented
> Is this one an updated version of #990?

No, this is a follow-up to #990, here it's only _transaction tests_, testing specifically new rules for when transactions are invalid.

(Not that we have not updated EIP text yet to make transactions with too big initcode invalid, sorry.
But the tests here consider them invalid)

2022-02-04 11:11 UTC, gumb0 commented
> (Not that we have not updated EIP text yet to make transactions with too big initcode invalid, sorry. But the tests here consider them invalid)

EIP is updated now. https://github.com/ethereum/EIPs/pull/4757

2022-02-08 16:58 UTC, jochem-brouwer commented
Ah yes this makes sense, we are not (yet) using the TransactionTests directory in JS, we should do that rather soon especially with these transactions. Thanks for the updates! :smile:

2022-03-02 21:08 UTC, jochem-brouwer commented
Note: TransactionTests only supports LegacyTransactions ATM, so #990 should also include state tests or blockchain tests for situations where (1) initcode of Tx (legacy/2929/1559) is longer than max initcode and (2) sender does not pay the upfront cost of initcode analysis.

2022-03-03 11:38 UTC, gumb0 commented
> Note: TransactionTests only supports LegacyTransactions ATM, so #990 should also include state tests or blockchain tests for situations where (1) initcode of Tx (legacy/2929/1559) is longer than max initcode and (2) sender does not pay the upfront cost of initcode analysis.

It might be possible to add TransactionTests with different transaction types, I'll check.

But adding them as state tests is also a good idea.

2022-05-30 19:12 UTC, jochem-brouwer commented
@gumb0 do these tests include tests regarding `CREATE/CREATE2` with sizes `maxInitCodeSize` and `maxInitCodeSize+1`?

2022-11-21 08:27 UTC, winsvega commented on src/TransactionTestsFiller/ttData/DataTestNotEnoughGasInitCodeFiller.yml
> +        London: ""
Is there an exception on London?

2022-11-21 08:29 UTC, winsvega commented on src/TransactionTestsFiller/ttData/DataTestInitCodeLimitFiller.yml
> +    expectException: {}
Is this field (expecException) required if its empty?

2022-11-22 12:25 UTC, winsvega requested changes
Update fork Merge+3860
Put EIP3860 in the test name or a new folder ttEIP3860
`London: ""`   in expectException can be deleted 
`expectException: {}` can be deleted

2022-11-29 15:57 UTC, gumb0 commented on src/TransactionTestsFiller/ttData/DataTestInitCodeTooBigFiller.yml
> +        Merge+3860: "TR_InitCodeLimitExceeded"
This requires a new mapping in retesteth config:
```
      "TR_InitCodeLimitExceeded" : "init code size limit exceeded",
```

2022-11-29 16:04 UTC, gumb0 commented
I would leave `Merge: ""` and `expectedException: {}` for explicitness, to show that we're testing that no exception is expected.

2022-11-30 16:24 UTC, winsvega commented on src/TransactionTestsFiller/ttEIP3860/DataTestNotEnoughGasInitCodeFiller.yml
> +        Merge+3860: "TR_IntrinsicGas"
add Merge+3860 in `additionalForks` section that is missing here. the test is not generated for this fork.

2022-11-30 16:25 UTC, winsvega commented on src/TransactionTestsFiller/ttEIP3860/DataTestInitCodeLimitFiller.yml
> +    expectException: {}
additionalforks Merge+3860

2022-11-30 16:25 UTC, winsvega commented on src/TransactionTestsFiller/ttEIP3860/DataTestEnoughGasInitCodeFiller.yml
> +    expectException: {}
additional forks Merge+3860

2022-11-30 16:27 UTC, winsvega requested changes
by default tests are generated for each fork in progression of Forks. 
but since you use fork+eip here, need to specify in the test that it should also be generated using fork+eip by defining it in additionalForks section in the test. 

retesteth config change no needed. 

good to have small trasaction unit tests here. very clear.

2022-12-01 14:49 UTC, winsvega commented on src/TransactionTestsFiller/ttEIP3860/DataTestNotEnoughGasInitCodeFiller.yml
> +        Merge: ""
if it is empty, then record not needed

2022-12-01 14:51 UTC, merged