EIP4758 test cases
ethereum/tests pull request #1024
Opened 2022-04-08 07:49 UTC by jwasinger

- [] SENDALL with self as beneficiary terminates execution of the current contract, leaves the current contract in the state after the transaction finishes.
- [] SENDALL with non-self beneficiary transfers the balance of the invoking account to the beneficiary, ends execution of the current frame.  The account which executed `SENDALL` remains in the state after the transaction finishes.

2022-11-22 12:30 UTC, winsvega commented
you can use lllc or yul in code src
this will also require to updated all our existing tests for selfdestruct when eip is accepted

2022-12-14 17:12 UTC, winsvega requested changes
need to move test to `EIPTests` subfolder. 
need to upgrade network naming to Merge+4758
index index section can be removed as it is -1 by default
src code can be used in yul or lllc

2022-12-14 17:12 UTC, winsvega commented on src/GeneralStateTestsFiller/stEIP4758/sendallToSelfFiller.json
> +                "network" : [">=EIP4758"],
need to convert to Merge+4758

2022-12-14 17:12 UTC, winsvega commented on src/GeneralStateTestsFiller/stEIP4758/sendallToSelfFiller.json
> +                "indexes" : {
indexes can be removed as it is -1 by default

2022-12-14 17:12 UTC, winsvega commented on src/GeneralStateTestsFiller/stEIP4758/sendallToSelfFiller.json
> +                "code" : ":raw 0x73095e7baea6a6c7c4c2dfeb977efac326af552d87ff",
can use lllc here or yul

2023-01-20 15:13 UTC, gumb0 commented
Would be good to add tests that check whether execution stops after SENDALL

2025-03-11 11:51 UTC, winsvega commented
@gumb0 shall it be ported to pyspecs?

2025-03-11 13:26 UTC, gumb0 commented
> @gumb0 shall it be ported to pyspecs?

Probably not, this EIP was abandoned in favor of EIP-6780

2025-03-11 13:55 UTC, jwasinger commented
Yup, this is very stale.

2025-03-11 13:55 UTC, closed without merging