EIP-5450: State Tests
ethereum/tests pull request #1163
Opened 2023-02-17 23:21 UTC by hugo-dc

2023-02-20 13:16 UTC, winsvega commented
please look at EOFTests its a whole new suite to develop the tests for EOF code. 
basically its just a state test format but simplified to focus only on EOF code deployment

2023-03-01 21:56 UTC, hugo-dc commented
@winsvega I have moved the validation tests to a [new file](https://github.com/ethereum/tests/blob/0b6245e593c4722c00b7b800755edb08268a37d0/src/EOFTestsFiller/EIP5450/validInvalidFiller.yml) using the validation format.

2023-03-01 22:07 UTC, winsvega commented
Just a question. Do we need eof code validation exception checks?
So that you can specify that this eof is invalid because of EOF header field has incorrect byte to verify that client t8n return expected error code?

2023-03-01 22:08 UTC, winsvega commented
Btw. Put the test vectors both in the test and /src/Readme.md

2023-03-02 16:37 UTC, hugo-dc commented
> Just a question. Do we need eof code validation exception checks? So that you can specify that this eof is invalid because of EOF header field has incorrect byte to verify that client t8n return expected error code?

Yes, that would be very helpful to really validate the invalid test are failing for the expected reason. Had an issue before when the test was failing but it was due to a  malformed EOF code instead of a different reason I was testing.

2023-04-14 13:55 UTC, winsvega commented on src/EOFTestsFiller/EIP5450/validInvalidFiller.yml
> +    # Code:
>=Cancun to autoenable exception on all future forks

2023-04-18 14:31 UTC, winsvega requested changes
needs rebase on develop.

2023-04-18 16:12 UTC, winsvega approved these changes

2023-04-18 16:13 UTC, merged