Tests for most of EIP2929 (except for SELFDESTRUCT).
ethereum/tests pull request #757
Opened 2020-11-16 22:15 UTC by qbzzt

1. The first time in a transaction that a storage cell or an address is referenced,
   the action is more expensive (compared to Istanbul, which is pre EIP2929)
2. Subsequent access is cheaper (again, compared to EIP2929)

This applies to:

Storage access:
SLOAD and SSTORE

Address access:
BALANCE
EXTCODESIZE
EXTCODECOPY
EXTCODEHASH
CALL
CALLCODE
DELEGATECALL
STATICCALL

2020-11-17 13:19 UTC, winsvega requested changes
Plus put a test for selfdestruct

2020-11-17 13:19 UTC, winsvega commented on src/GeneralStateTestsFiller/stEIP150singleCodeGasPrices/eip2929Filler.yml
> +        - :abi f(uint,uint,uint) 1 1 1
Use ":label foo"

2020-11-18 02:25 UTC, qbzzt commented on src/GeneralStateTestsFiller/stEIP150singleCodeGasPrices/eip2929Filler.yml
> +        - :abi f(uint,uint,uint) 1 1 1
Done

2020-11-18 04:11 UTC, qbzzt commented
> Plus put a test for selfdestruct

Done, `eip2929-ff` (because I didn't want to write a long name such as `eip2929-self-destruct`. It checks all the ways in which an address can become accessed, and also that the selfdestruct itself makes the address accessed if it wasn't before.

2020-11-18 08:36 UTC, winsvega requested changes
Ok. Now need a retesteth folder update. And --filltests --fillchain

2020-11-18 13:00 UTC, qbzzt commented
I already did the --filltests for this test.

I will do the doc updates for the retesteth changes soon, probably over the
weekend.

On Wed, Nov 18, 2020, 2:37 AM winsvega <notifications@github.com> wrote:

> *@winsvega* requested changes on this pull request.
>
> Ok. Now need a retesteth folder update. And --filltests --fillchain
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum/tests/pull/757#pullrequestreview-533209566>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADBCGGMQESVL65BXUO76F6TSQOBSXANCNFSM4TXYQ5WA>
> .
>

2020-11-21 00:20 UTC, winsvega commented
I see. Checkhash doesn't detect new tests missing in blockchain format

2020-11-22 15:10 UTC, winsvega commented
moved to https://github.com/ethereum/tests/pull/760

2020-11-22 15:10 UTC, closed without merging