When an opcode receives an address > 2^160, what happens?
ethereum/tests pull request #766
Opened 2020-11-30 01:22 UTC by qbzzt

Ensure the least significant 160 bits are used and the rest are truncated

2020-12-07 19:50 UTC, winsvega requested changes
1)

```
(call 0x1000 @addr1 0 0x2000 0x20 res1 word)
             (call 0x1000 @addr2 0 0x2000 0x20 res2 word)
```

would feel safer to have  
res1 == res2 == "expected result"

2)
please double check with vmtrace that the stack for opcodes does actually contain a value with (2**160 + adress)  for the second case.  I would not blindly trust the lll compiler to do that.

2020-12-08 02:58 UTC, qbzzt commented
> please double check with vmtrace that the stack for opcodes does actually contain a value with (2**160 + adress) for the second case. I would not blindly trust the lll compiler to do that.

Done. The values for `addr2` are the expected ones.

2020-12-08 03:30 UTC, qbzzt commented
> would feel safer to have
> res1 == res2 == "expected result"

Then you can feel safe now ;-)

2020-12-12 13:34 UTC, winsvega approved these changes

2020-12-12 13:38 UTC, merged