Random tests
ethereum/tests pull request #949
Opened 2021-10-01 18:12 UTC by qbzzt

1. Generate a random state test
2. Fill the test on `geth`
3. Run the filled test on `besu`
4. If it fails, copy to `/tmp` under a unique name
5. Go to step 1 (endless loop)

Not included yet (I'll do them when I have time): calls to precompiles.

2021-10-17 10:49 UTC, winsvega commented on src/Templates/RandomTests/README.md
> +1. Run `./runTests.sh`. It is an endless loop that generates and runs
can you make options for this script 
- testpath  
- docker / retesteth (when retesteth then original datadir by default is used)
- StateTest / BlockchainTest
- rounds <num> / unlimited (limit loop for testing)
- errored test output dir

2021-10-17 10:51 UTC, winsvega commented on src/Templates/RandomTests/oneTest.sh
> +                --filltests --datadir /tests/config
what if geth fails on test filling ?
should be reported too

2021-10-17 10:52 UTC, winsvega requested changes
add options to the script so I can run it on vps

2021-10-18 21:03 UTC, qbzzt commented on src/Templates/RandomTests/oneTest.sh
> +                --filltests --datadir /tests/config
Added

2021-10-19 01:57 UTC, qbzzt commented on src/Templates/RandomTests/README.md
> +1. Run `./runTests.sh`. It is an endless loop that generates and runs
[] testpath
[] docker / retesteth (when retesteth then original datadir by default is used)
[] StateTest / BlockchainTest
[] rounds / unlimited (limit loop for testing)
[] errored test output dir

2021-10-25 19:02 UTC, qbzzt commented on src/Templates/RandomTests/README.md
> +1. Run `./runTests.sh`. It is an endless loop that generates and runs
I created all of those command line options. I still need to:

1. Update the README.md
2. Finish what I'm writing to have an explanation of the code.

2021-11-06 11:21 UTC, winsvega commented
should keep in mind that besu require javahome to be set 
    `export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64`
for me it seems `JAVA_HOME` could not be set through `/etc/environment`
so I set it manually every time.

2021-11-06 21:06 UTC, qbzzt commented
> should keep in mind that besu require javahome to be set `export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64` for me it seems `JAVA_HOME` could not be set through `/etc/environment` so I set it manually every time.
> 
> also example command: `./runTests.sh -n 1 -e /data/rndtests -r`
> 
> unfortunately on vps besu does not work (((

`oneTests.sh` doesn't run Besu, it connects to be an existing instance (specified in the retesteth config). So Besu can just as easily run in a VM outside the vps.

2021-12-09 20:03 UTC, winsvega commented
can you name the test a little bit simplier. and the name inside of a test file should match the name of test file
because thats the rule we made for state tests

2021-12-10 03:51 UTC, qbzzt commented
> can you name the test a little bit simplier. and the name inside of a test file should match the name of test file
> because thats the rule we made for state tests

Consider it done. The name is now <type of test>-<uuid>Filler.yml.

2021-12-17 15:47 UTC, winsvega approved these changes

2021-12-17 15:47 UTC, merged