Add EIP-3607 tests for Sender not EOA
ethereum/tests pull request #963
Opened 2021-10-13 00:26 UTC by marioevz

This PR closes #952 .
The following test cases are included:
- An account with non-empty code sends the following transactions: send value, calls a contract, calls itself, deploys contract, init code executes: call, delegatecall
- An account with empty code attempts to init into a non-empty code address: contract deployment to non-empty address, init code executes: call, delegatecall, create, create2

All tests are negative test cases and correctly fail.

This PR excludes tests where create and create2 deploy to an existing address since this is already tested by: GeneralStateTests/stCreate2, GeneralStateTests/stCreateTest

2021-10-13 07:09 UTC, holiman commented
Just reading the description, I think this PR might be a bit over-ambitious? 
The thing is, _any_ transaction made from a non-EOA account should be rejected out of hand. So I think it would be sufficient to test whether a basic 'send ether to a recipient', 'make a create-tx' are rejected or not. That said, I'm fine with it being as it is, just noting my thoughts. 

Also, to clarify; this change should be retroactive, so could be extended for pre-berlin aswell, but that's not important either.

2021-10-13 15:52 UTC, marioevz commented
Thanks for the feedback, what I had in mind was that perhaps other clients implemented this differently and adding some extra checks just to be safe would be ok, but if everyone is inclined to reduce the number of test cases, that is also ok by me.
Also, I will change the fork to be retroactive.
Thanks again.

2021-10-13 17:42 UTC, qbzzt commented
> Thanks for the feedback, what I had in mind was that perhaps other clients implemented this differently and adding some extra checks just to be safe would be ok, but if everyone is inclined to reduce the number of test cases, that is also ok by me. 

My opinion is that having a few extra tests won't hurt anything, and might save us from an unspecified error in the future.

2021-10-13 18:55 UTC, MariusVanDerWijden commented
Reminder to self: selfdestruct a contract and send a tx from it after

2021-10-13 23:06 UTC, marioevz commented
> Reminder to self: selfdestruct a contract and send a tx from it after

Added this test case in the latest commit.
I first tried the contract to send the self-destruct funds to itself, but since the account is deleted, the funds also are destroyed.

The test case I ended up writing:
- Self-destruct sends the funds to another account
- This other account returns the funds to the address that just self-destructed
- The funds are then finally retrieved with the secretKey

Let me know if this is ok.
Thanks.

2021-10-14 06:49 UTC, holiman commented
> Let me know if this is ok.

:+1: Looks good to me!

2021-10-15 17:03 UTC, winsvega requested changes
I think can merge many tests into one and use data as array.

2021-10-15 17:03 UTC, winsvega commented on src/GeneralStateTestsFiller/stEIP3607/nonEmptyAccount_initsFiller.yml
> +    - ':raw 0x00'
you can define multiple data raws here. 
all the transactions would get rejected. I don't think there is a much need to cover every possible init data code. 
but because each state test is translated into bc test for each fork here. please limit the amount of tests. 
if the pre state is the same you can define it in one file with different data raws.

2021-10-15 17:03 UTC, winsvega commented on src/GeneralStateTestsFiller/stEIP3607/nonEmptyAccount_contractDeployFiller.yml
> +    to: ''
the 2 cases here is really when transaction has destination. 
and the second when it runs creation. (empty to) this are 2 different files

2021-10-15 17:03 UTC, winsvega commented on src/GeneralStateTestsFiller/stEIP3607/initNonEmptyAccount_callFiller.yml
> +initNonEmptyAccount_call:
this is an interesting case. collision and wrong sender at the same time.

2021-10-15 17:05 UTC, winsvega commented
yes a good test case but in blockchain test within one block
first transaction destroys the account (selfdestruct) 
second one is coming from the destroyed account. (should be valid now, but fail due to the account empty balance)

2021-10-15 19:42 UTC, marioevz commented
> yes a good test case but in blockchain test within one block

Yes this was created as a blockchain test in src/BlockchainTestsFiller/ValidBlocks/bcStateTests/contractSuicideThenSendFiller.yml

Also reduced the number of files as suggested in latest commit, and changed the fork to ">=London" to generate less tests.

2021-10-15 21:48 UTC, winsvega requested changes

2021-10-15 21:48 UTC, winsvega commented on src/GeneralStateTestsFiller/stEIP3607/nonEmptyAccount_initFiller.yml
> +        - '>=London'
ok here could be >=Frontier

2021-10-15 21:48 UTC, winsvega commented on src/GeneralStateTestsFiller/stEIP3607/nonEmptyAccount_callsFiller.yml
> +      code: ':raw 0xdeadbeef'
put something meaningfull like  0x6000600155

2021-10-15 21:48 UTC, winsvega commented on src/GeneralStateTestsFiller/stEIP3607/nonEmptyAccount_callsFiller.yml
> +        - '>=London'
here >=Frontiner

2021-10-15 21:48 UTC, winsvega commented on src/GeneralStateTestsFiller/stEIP3607/initNonEmptyAccountFiller.yml
> +initNonEmptyAccount:
put here that collision involved

2021-10-15 21:48 UTC, winsvega commented on src/GeneralStateTestsFiller/stEIP3607/initNonEmptyAccountFiller.yml
> +        6295ee1b4f6dd65047762f924ecd367c17eabf8f:
check a94f5374fce5edbc8e2a8697c15331677e6ebf0b  nonce

2021-10-15 21:48 UTC, winsvega commented on src/BlockchainTestsFiller/ValidBlocks/bcStateTests/contractSuicideThenSendFiller.yml
> +      code: :raw 0x737ae27a42774a1f034ac7edb93d23cb5a662017d5FF
source code???

2021-10-15 21:48 UTC, winsvega commented on src/BlockchainTestsFiller/ValidBlocks/bcStateTests/contractSuicideThenSendFiller.yml
> +      gasLimit: 21000
put more gaslimit as it tend to change to higher number in the future forks

2021-10-15 21:48 UTC, winsvega commented on src/BlockchainTestsFiller/ValidBlocks/bcStateTests/contractSuicideThenSendFiller.yml
> +contractSuicideThenSend:
transaction from selfdestruct

2021-10-15 21:48 UTC, winsvega commented on src/BlockchainTestsFiller/ValidBlocks/bcStateTests/contractSuicideThenSendFiller.yml
> +      0xfebc70C40FadB14d796F1d499b3f247e12FBbd94:
check nonce

2021-10-17 10:29 UTC, merged