Remove BasicTests Folder
ethereum/tests pull request #976
Opened 2021-10-31 03:47 UTC by marioevz

This PR removes the BasicTests folder which has been relocated to the ethereum/legacytests repo.

2021-10-31 10:37 UTC, winsvega commented
there are some files that might still be used by someone. 
those are really legacy tests, cause it was here before the frontier eve

2021-11-01 10:36 UTC, winsvega requested changes
lets move to legacy only the difficulty tests 
legacytests root / BasicTests / *olddifficulty tests

2021-11-01 10:36 UTC, winsvega commented on BasicTests/blockgenesistest.json
> -[
I have no idea how many teams are still using this files. perhaps it is better to leave it here as it is small

2021-11-01 10:36 UTC, winsvega commented on BasicTests/crypto.json
> -{
I have no idea how many teams are still using this files. perhaps it is better to leave it here as it is small

2021-11-01 10:36 UTC, winsvega commented on BasicTests/genesishashestest.json
> -{
I have no idea how many teams are still using this files. perhaps it is better to leave it here as it is small

2021-11-01 10:36 UTC, winsvega commented on BasicTests/hexencodetest.json
> -{
I have no idea how many teams are still using this files. perhaps it is better to leave it here as it is small

2021-11-01 10:36 UTC, winsvega commented on BasicTests/keyaddrtest.json
> -[
I have no idea how many teams are still using this files. perhaps it is better to leave it here as it is small

2021-11-01 10:36 UTC, winsvega commented on BasicTests/txtest.json
> -    {
I have no idea how many teams are still using this files. perhaps it is better to leave it here as it is small

2021-11-01 10:46 UTC, holiman commented
As for go-ethereum, we use the BasicTests in this file: https://github.com/ethereum/go-ethereum/blob/master/tests/difficulty_test.go#L84 -- it is the `difficultyTestDir`. 

We skip these: 
```
	dt.skipLoad("hexencodetest.*")
	dt.skipLoad("crypto.*")
	dt.skipLoad("blockgenesistest\\.json")
	dt.skipLoad("genesishashestest\\.json")
	dt.skipLoad("keyaddrtest\\.json")
	dt.skipLoad("txtest\\.json")
```
And these: 
```
	// files are 2 years old, contains strange values
	dt.skipLoad("difficultyCustomHomestead\\.json")
	dt.skipLoad("difficultyMorden\\.json")
	dt.skipLoad("difficultyOlimpic\\.json")
```

2021-11-01 10:47 UTC, holiman commented
For all changes such as these, please make sure to write them up on the release notes, eventually, so we can make sure to update and use the new paths.

2021-11-01 10:49 UTC, winsvega commented
yes. the existing difficulty tests we plan to move to LegacyTests subfolder (repo)
and have a copy of them in a new difficulty test format https://github.com/ethereum/tests/pull/970
with new tests to cover arrowGlacier as well.

2021-11-01 17:10 UTC, marioevz commented
I think that partially removing some of the files might end up being more confusing to the users instead of simply instructing:
"./BasicTests is now at ./LegacyTests/BasicTests, be sure to add '--recurse-submodules' when cloning this repo to obtain these files if you require them", or something similar.
Let me know what you think @holiman @winsvega

2021-11-01 17:54 UTC, winsvega commented
for thise little files it does not make much sense to fetch the whole legacy tests repo. 
removing old difficulty tests to legacy repo is what we want. it will make everyone notice that there are new difficulty tests

2021-11-01 18:01 UTC, marioevz commented
Got it, sounds good. Will remove only what's being updated in #977, everything else remains in ./BasicTests .
For ethereum/legacytests#1, I added everything under ./BasicTests -> ./LegacyTests/BasicTests, but will update to only add files removed in this PR.

2021-11-01 19:19 UTC, merged